/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyStats {
  'totalOrders' : bigint,
  'completedOrders' : bigint,
  'totalRevenue' : number,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'customerPhone' : string,
  'createdAt' : bigint,
  'orderDate' : string,
  'totalAmount' : number,
  'products' : Array<OrderItem>,
}
export interface OrderItem {
  'unit' : string,
  'productId' : bigint,
  'quantity' : number,
}
export interface Product {
  'id' : bigint,
  'nameEn' : string,
  'nameTe' : string,
  'pricePerKg' : number,
  'isAvailable' : boolean,
  'description' : string,
  'category' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyStats' : ActorMethod<[string], DailyStats>,
  'getOrders' : ActorMethod<[string], Array<Order>>,
  'getProductImages' : ActorMethod<[], Array<[string, string]>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getSiteMediaImages' : ActorMethod<[], Array<[string, string]>>,
  'getTodayOrders' : ActorMethod<[], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeProducts' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[string, string, Array<OrderItem>], bigint>,
  'removeProductImage' : ActorMethod<[string], undefined>,
  'removeSiteMediaImage' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProductImage' : ActorMethod<[string, string], undefined>,
  'saveSiteMediaImage' : ActorMethod<[string, string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
  'updateProductRate' : ActorMethod<[bigint, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];